# без version:

x-env: &default-env
  AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
  AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

networks:
  rt_net:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  pg_data:
  airflow_logs:
  airflow_plugins:
  airflow_dags:
  zk_data:
  kafka_data:

services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOO_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOO_PORT}:2181"
    networks: [rt_net]
    volumes:
      - zk_data:/var/lib/zookeeper
    # ПРОСТОЙ HEALTHCHECK: проверяем, что порт слушает
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/2181'"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  kafka:
    image: ${KAFKA_IMAGE}
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "${KAFKA_PORT}:9092"        # localhost:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOO_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:${KAFKA_PORT},INTERNAL://kafka:${KAFKA_INTERNAL_PORT}
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:${KAFKA_INTERNAL_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks: [rt_net]
    healthcheck:
      # любой лёгкий ping; подойдёт cli из образа
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20


  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rt_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rt_password}
      POSTGRES_DB: ${POSTGRES_DB:-rt_db}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [rt_net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 20

  airflow-init:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow-init
    entrypoint: /bin/bash
    command: |
      -c "
      set -e
      mkdir -p /opt/airflow/dags /opt/airflow/logs /opt/airflow/plugins
      chown -R ${AIRFLOW_UID}:0 /opt/airflow
      su -s /bin/bash airflow -c \"airflow db migrate && airflow users create --username ${AIRFLOW_ADMIN_USERNAME} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname ${AIRFLOW_ADMIN_FIRSTNAME:-Admin} --lastname ${AIRFLOW_ADMIN_LASTNAME:-User} --role Admin --email ${AIRFLOW_ADMIN_EMAIL}\"
      "
    environment:
      <<: *default-env
      AIRFLOW_UID: ${AIRFLOW_UID}
    user: "0:0"
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    networks: [rt_net]
    restart: "no"




  airflow-webserver:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: webserver
    environment:
      <<: *default-env
    user: "${AIRFLOW_UID}:0"
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [rt_net]
    restart: unless-stopped

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: scheduler
    environment:
      <<: *default-env
    user: "${AIRFLOW_UID}:0"
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    networks: [rt_net]
    restart: unless-stopped


  airflow-triggerer:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow-triggerer
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: triggerer
    environment:
      <<: *default-env
    user: "${AIRFLOW_UID}:0"
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    networks: [rt_net]
    restart: unless-stopped

